apiVersion: v1
kind: Service
metadata:
  name: stratum-backend
  labels:
    app: stratum-backend
spec:
  type: ClusterIP
  selector:
    app: stratum-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
