services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    image: stratum-backend:dev

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    image: stratum-frontend:dev
